version: "3.1"
services:
  database:
    image: postgres:10.1
    ports:
      - "5433:5432"
    expose:
      - "5433"
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres

    networks:
      - back-end


  redis:
    image: redis
    ports:
      - "6379:6379"
    networks:
      - back-end

  weconnect:
    restart: always
    build:
      context: .
      dockerfile: docker/Dockerfile
    ports:
      - "8000:8000"
    image: weconnect-image
    volumes:
      - .:/usr/weconnect
    depends_on:
      - redis
      - database
    stdin_open: true
    tty: true
    environment:
      - DATABASE_URL=postgres://postgres:postgres@database:5432/postgres
      - CELERY_BROKER_URL=redis://redis
      - CELERY_RESULT_BACKEND=redis://redis
      - DB_NAME=postgres
      - DB_PASSWORD=postgres
      - DB_USER=postgres
      - DB_HOST=database
    networks:
      - back-end

volumes:
  pgdata:

networks:
  back-end: